<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissionNames = [
            'admin.lote.update',
            'bancas.cargar',
            'bancas.create',
            'bancas.destroy',
            'bancas.edit',
            'bancas.index',
            'bancas.movimientos',
            'bancas.show',
            'bancas.store',
            'bancas.update',
            'caja.apertura',
            'caja.cierre',
            'caja.index',
            'caja.movimientos',
            'caja.reportes',
            'categorias.create',
            'categorias.destroy',
            'categorias.edit',
            'categorias.index',
            'categorias.show',
            'categorias.store',
            'categorias.update',
            'clientes.create',
            'clientes.destroy',
            'clientes.edit',
            'clientes.index',
            'clientes.show',
            'clientes.store',
            'clientes.update',
            'compras.correccion',
            'compras.create',
            'compras.destroy',
            'compras.edit',
            'compras.enviarCorreo',
            'compras.finalizarCompra',
            'compras.index',
            'compras.procesarCarrito',
            'compras.show',
            'compras.store',
            'cotizaciones.aplicar-descuento',
            'cotizaciones.convertir',
            'cotizaciones.create',
            'cotizaciones.destroy',
            'cotizaciones.edit',
            'cotizaciones.imprimir',
            'cotizaciones.index',
            'cotizaciones.show',
            'cotizaciones.store',
            'cotizaciones.update',
            'inventario.stock_bajo.pdf',
            'inventario.stock_bajo_sucursal',
            'inventario.sucursal.pdf',
            'lotes.create',
            'lotes.destroy',
            'lotes.edit',
            'lotes.index',
            'lotes.pdf',
            'lotes.show',
            'lotes.store',
            'lotes.update',
            'lotes.vencidos',
            'lotes.vencidos.agregar',
            'lotes.vencidos.eliminar',
            'lotes.vencidos.finalizar',
            'lotes.vencidos.sucursal',
            'mostrar_inventario_por_sucursal.show',
            'movimientos.index',
            'operaciones.todas-sucursales',
            'pagos.create',
            'pagos.destroy',
            'pagos.index',
            'pagos.store',
            'productos.create',
            'productos.desactivar',
            'productos.destroy',
            'productos.edit',
            'productos.index',
            'productos.show',
            'productos.store',
            'productos.ultimo-codigo',
            'productos.update',
            'productos.verificar-codigo',
            'proveedores.destroy',
            'proveedores.index',
            'proveedores.store',
            'proveedores.update',
            'reportes.vendedores',
            'reportes.ventas',
            'reportes.ventas.diario',
            'reportes.ventas.mensual',
            'roles.create',
            'roles.destroy',
            'roles.edit',
            'roles.index',
            'roles.permisos',
            'roles.store',
            'roles.update',
            'roles.update_permisos',
            'salidas.create',
            'salidas.destroy',
            'salidas.edit',
            'salidas.finalizarSalida',
            'salidas.index',
            'salidas.show',
            'salidas.store',
            'sucursal_por_lotes.index',
            'sucursales.create',
            'sucursales.destroy',
            'sucursales.edit',
            'sucursales.index',
            'sucursales.show',
            'sucursales.store',
            'sucursales.update',
            'tipo_cambio.bs-a-usd',
            'tipo_cambio.destroy',
            'tipo_cambio.index',
            'tipo_cambio.recalcular-venta',
            'tipo_cambio.store',
            'tipo_cambio.update',
            'tipo_cambio.usd-a-bs',
            'user.assign-roles',
            'user.create',
            'user.destroy',
            'user.edit',
            'user.index',
            'user.store',
            'user.update',
            'ventas.anular',
            'ventas.aplicar-descuento',
            'ventas.create',
            'ventas.destroy',
            'ventas.edit',
            'ventas.index',
            'ventas.modificar-precio',
            'ventas.show',
            'ventas.store',
            'ventas.update',
        ];

        $permissions = collect($permissionNames)->mapWithKeys(function (string $name) {
            $permission = Permission::firstOrCreate(['name' => $name, 'guard_name' => 'web']);
            return [$name => $permission];
        });

        $superadmin = Role::firstOrCreate(['name' => 'superadmin', 'guard_name' => 'web']);
        $admin = Role::firstOrCreate(['name' => 'admin', 'guard_name' => 'web']);
        $vendedor = Role::firstOrCreate(['name' => 'vendedor', 'guard_name' => 'web']);
        $cajero = Role::firstOrCreate(['name' => 'cajero', 'guard_name' => 'web']);
        $almacen = Role::firstOrCreate(['name' => 'almacen', 'guard_name' => 'web']);

        // El Superadministrador es un perfil de supervisión global. Puede
        // consultar todas las sucursales, generar reportes y administrar
        // usuarios/roles, pero no registra ni modifica operaciones del negocio.
        $permisosSuperadmin = [
            'operaciones.todas-sucursales',
            'bancas.index',
            'bancas.movimientos',
            'bancas.show',
            'caja.index',
            'caja.reportes',
            'categorias.index',
            'categorias.show',
            'clientes.index',
            'clientes.show',
            'compras.index',
            'compras.show',
            'cotizaciones.imprimir',
            'cotizaciones.index',
            'cotizaciones.show',
            'inventario.stock_bajo.pdf',
            'inventario.stock_bajo_sucursal',
            'inventario.sucursal.pdf',
            'lotes.index',
            'lotes.pdf',
            'lotes.show',
            'lotes.vencidos',
            'lotes.vencidos.sucursal',
            'mostrar_inventario_por_sucursal.show',
            'movimientos.index',
            'pagos.index',
            'productos.index',
            'productos.show',
            'proveedores.index',
            'reportes.vendedores',
            'reportes.ventas',
            'reportes.ventas.diario',
            'reportes.ventas.mensual',
            'roles.index',
            'roles.permisos',
            'roles.update_permisos',
            'salidas.index',
            'salidas.show',
            'sucursal_por_lotes.index',
            'sucursales.index',
            'sucursales.show',
            'tipo_cambio.bs-a-usd',
            'tipo_cambio.index',
            'tipo_cambio.usd-a-bs',
            'user.assign-roles',
            'user.create',
            'user.destroy',
            'user.edit',
            'user.index',
            'user.store',
            'user.update',
            'ventas.index',
            'ventas.show',
        ];
        $superadmin->syncPermissions($permissions->only($permisosSuperadmin)->values());

        // El administrador trabaja únicamente en la sucursal asignada y
        // administra la operación de esa sucursal. La gestión de usuarios y
        // roles queda reservada al Superadministrador.
        $permisosSoloSuperadmin = [
            'operaciones.todas-sucursales',
            'sucursales.create',
            'sucursales.destroy',
            'sucursales.edit',
            'sucursales.index',
            'sucursales.show',
            'sucursales.store',
            'sucursales.update',
            'roles.create',
            'roles.destroy',
            'roles.edit',
            'roles.index',
            'roles.permisos',
            'roles.store',
            'roles.update',
            'roles.update_permisos',
            'user.assign-roles',
            'user.create',
            'user.destroy',
            'user.edit',
            'user.index',
            'user.store',
            'user.update',
        ];

        $permisosAdminSucursal = $permissions
            ->reject(fn ($permission, string $name) => in_array($name, $permisosSoloSuperadmin, true))
            ->values();
        $admin->syncPermissions($permisosAdminSucursal);

        $vendedor->syncPermissions($permissions->only([
            'caja.apertura',
            'caja.cierre',
            'caja.index',
            'clientes.create',
            'clientes.edit',
            'clientes.index',
            'clientes.show',
            'clientes.store',
            'clientes.update',
            'cotizaciones.aplicar-descuento',
            'cotizaciones.convertir',
            'cotizaciones.create',
            'cotizaciones.imprimir',
            'cotizaciones.index',
            'cotizaciones.show',
            'cotizaciones.store',
            'pagos.create',
            'pagos.index',
            'pagos.store',
            'productos.index',
            'productos.show',
            'sucursal_por_lotes.index',
            'mostrar_inventario_por_sucursal.show',
            'inventario.stock_bajo_sucursal',
            'reportes.ventas',
            'reportes.ventas.diario',
            'ventas.aplicar-descuento',
            'ventas.create',
            'ventas.index',
            'ventas.show',
            'ventas.store',
        ])->values());

        $cajero->syncPermissions($permissions->only([
            'caja.apertura',
            'caja.cierre',
            'caja.index',
            'pagos.create',
            'pagos.index',
            'pagos.store',
            'reportes.ventas',
            'reportes.ventas.diario',
            'ventas.index',
            'ventas.show',
        ])->values());

        $almacen->syncPermissions($permissions->only([
            'categorias.create',
            'categorias.destroy',
            'categorias.edit',
            'categorias.index',
            'categorias.show',
            'categorias.store',
            'categorias.update',
            'compras.correccion',
            'compras.create',
            'compras.destroy',
            'compras.edit',
            'compras.enviarCorreo',
            'compras.finalizarCompra',
            'compras.index',
            'compras.procesarCarrito',
            'compras.show',
            'compras.store',
            'inventario.stock_bajo.pdf',
            'inventario.stock_bajo_sucursal',
            'inventario.sucursal.pdf',
            'sucursal_por_lotes.index',
            'mostrar_inventario_por_sucursal.show',
            'lotes.index',
            'lotes.show',
            'lotes.vencidos',
            'lotes.vencidos.sucursal',
            'lotes.vencidos.agregar',
            'lotes.vencidos.eliminar',
            'lotes.vencidos.finalizar',
            'admin.lote.update',
            'movimientos.index',
            'productos.create',
            'productos.desactivar',
            'productos.destroy',
            'productos.edit',
            'productos.index',
            'productos.show',
            'productos.store',
            'productos.ultimo-codigo',
            'productos.update',
            'productos.verificar-codigo',
            'proveedores.destroy',
            'proveedores.index',
            'proveedores.store',
            'proveedores.update',
            'salidas.create',
            'salidas.destroy',
            'salidas.edit',
            'salidas.finalizarSalida',
            'salidas.index',
            'salidas.show',
            'salidas.store',
        ])->values());

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
